---
- hosts: all
  become: true

  tasks:
    - name: Install tomcat
      apt:
        name: "{{ item }}"
        state: present
      loop:
      - default-jdk
      - tomcat9
 
    - name: Start tomcat
      systemd:
        name: tomcat9
        state: started
        daemon_reload: true

    - name: Add uesr to tomcat group
      user:
        name: "{{ ansible_user }}"
        group: tomcat

    - name: Update WAR deployment
      copy:
        src: ../target/SpringBootWeb.war
        dest: /var/lib/tomcat9/webapps
        group: tomcat
        mode: '0775'
      notify: Restart Tomcat

  handlers:
    - name: Restart Tomcat
      service:
        name: tomcat9
        state: restarted
